### ISSUE TITLE
How to run GazeNet?

### ISSUE THREAD

**Issue by akatav** [zdarsky/GazeNet#2]
Hi
I downloaded your code. Thanks for making it available online. 
I am wondering if you could add a README. 

I ran the gazerec.py, the frame comes up at the right corner of my laptop screen. But, nothing happens after that. 

I am looking for 2D gaze point estimation.

**Comment by zdarsky** [comment]
Hello @akatav,

sorry for the late response, I didn't get any notification on this issue.

Is there any output in the console?
I added an environment.yml file so you can compare the versions of dependencies.

You might need to tweak some values in the code as there are hardcoded values sprinkled in which affect the output based on your resolution (I used a 2560x1440 screen) and webcam.

At the beginning of the script, a webcam test frame is displayed which should show you a cropped output of your webcam. When you are satisfied with it, you have to press "e" to continue with the recording.
