### ISSUE TITLE
Can you help running GazeNet?

### ISSUE THREAD

**Issue by fernandasdias** [zdarsky/GazeNet#3]
Hi, 

I tried running gazerec.py but nothing works. I can execute the test_rec(), but nothing aside from it. 

Could you please help me?
thanks

**Comment by zdarsky** [comment]
Hello @fernandasdias,

sorry for the late response, I didn't get any notification on this issue.

Is there any output in the console?
I added an environment.yml file so you can compare the versions of dependencies.

Also have a look at #2 for slightly more info.

**Comment by FernandaKey** [comment]
Thanks a lot!
