### ISSUE TITLE
How to train the model?

### ISSUE THREAD

**Issue by Rangel07** [zdarsky/GazeNet#4]
I'm having issues with running GazeNet.

I passed through `gazerec.py` successfully and created the data (gazedots.csv and images). But I couldn't figure out how to train the model using the data recorded.

Is there a external code to use DeepLabCut that I could use to transform the data before using it in `main.py`? Or it would be possible to describe the inputs needed to GazeNet?

Congratulations for the project and thanks in advance! :smile:

**Comment by zdarsky** [comment]
Hi @Rangel07 ,

can you post the first couple of lines of the CSV that got extracted by DeepLabCut that you are trying to load into `main.py`? Mine looks like this:

<pre><code>
scorer,DLC_resnet50_attentiontestFeb19shuffle1_45000,DLC_resnet50_attentiontestFeb19shuffle1_45000,DLC_resnet50_attentiontestFeb19shuffle1_45000,DLC_resnet50_attentiontestFeb19shuffle1_45000,DLC_resnet50_attentiontestFeb19shuffle1_45000,DLC_resnet50_attentiontestFeb19shuffle1_45000,DLC_resnet50_attentiontestFeb19shuffle1_45000,DLC_resnet50_attentiontestFeb19shuffle1_45000,DLC_resnet50_attentiontestFeb19shuffle1_45000,DLC_resnet50_attentiontestFeb19shuffle1_45000,DLC_resnet50_attentiontestFeb19shuffle1_45000,DLC_resnet50_attentiontestFeb19shuffle1_45000,DLC_resnet50_attentiontestFeb19shuffle1_45000,DLC_resnet50_attentiontestFeb19shuffle1_45000,DLC_resnet50_attentiontestFeb19shuffle1_45000,DLC_resnet50_attentiontestFeb19shuffle1_45000,DLC_resnet50_attentiontestFeb19shuffle1_45000,DLC_resnet50_attentiontestFeb19shuffle1_45000,DLC_resnet50_attentiontestFeb19shuffle1_45000,DLC_resnet50_attentiontestFeb19shuffle1_45000,DLC_resnet50_attentiontestFeb19shuffle1_45000,DLC_resnet50_attentiontestFeb19shuffle1_45000,DLC_resnet50_attentiontestFeb19shuffle1_45000,DLC_resnet50_attentiontestFeb19shuffle1_45000,DLC_resnet50_attentiontestFeb19shuffle1_45000,DLC_resnet50_attentiontestFeb19shuffle1_45000,DLC_resnet50_attentiontestFeb19shuffle1_45000,DLC_resnet50_attentiontestFeb19shuffle1_45000,DLC_resnet50_attentiontestFeb19shuffle1_45000,DLC_resnet50_attentiontestFeb19shuffle1_45000,DLC_resnet50_attentiontestFeb19shuffle1_45000,DLC_resnet50_attentiontestFeb19shuffle1_45000,DLC_resnet50_attentiontestFeb19shuffle1_45000,DLC_resnet50_attentiontestFeb19shuffle1_45000,DLC_resnet50_attentiontestFeb19shuffle1_45000,DLC_resnet50_attentiontestFeb19shuffle1_45000,DLC_resnet50_attentiontestFeb19shuffle1_45000,DLC_resnet50_attentiontestFeb19shuffle1_45000,DLC_resnet50_attentiontestFeb19shuffle1_45000
bodyparts,leftLeftEdge,leftLeftEdge,leftLeftEdge,leftRightEdge,leftRightEdge,leftRightEdge,leftLeftPupil,leftLeftPupil,leftLeftPupil,leftTopPupil,leftTopPupil,leftTopPupil,leftRightPupil,leftRightPupil,leftRightPupil,leftBottomPupil,leftBottomPupil,leftBottomPupil,rightLeftEdge,rightLeftEdge,rightLeftEdge,rightRightEdge,rightRightEdge,rightRightEdge,rightLeftPupil,rightLeftPupil,rightLeftPupil,rightTopPupil,rightTopPupil,rightTopPupil,rightRightPupil,rightRightPupil,rightRightPupil,rightBottomPupil,rightBottomPupil,rightBottomPupil,upperLip,upperLip,upperLip
coords,x,y,likelihood,x,y,likelihood,x,y,likelihood,x,y,likelihood,x,y,likelihood,x,y,likelihood,x,y,likelihood,x,y,likelihood,x,y,likelihood,x,y,likelihood,x,y,likelihood,x,y,likelihood,x,y,likelihood
0,106.61483764648438,352.84564208984375,0.9999796152114868,162.91885375976562,350.98358154296875,0.9994847774505615,120.02276611328125,351.1368103027344,0.999997615814209,123.34374237060547,348.8249816894531,0.9999792575836182,128.7569122314453,350.1414489746094,0.9999850988388062,123.15386199951172,355.0992431640625,0.9999983310699463,230.13449096679688,319.40869140625,0.9999828338623047,276.7274475097656,309.73968505859375,0.9999874830245972,247.9342803955078,310.6781921386719,0.9999966621398926,251.7943572998047,307.333740234375,0.9999953508377075,255.50503540039062,310.571044921875,0.9999889135360718,251.1327667236328,314.7654724121094,0.9999716281890869,240.2589569091797,459.3399353027344,0.9999052286148071
1,106.48544311523438,352.5255432128906,0.9999823570251465,162.9788360595703,350.8147888183594,0.9995212554931641,120.09046936035156,350.97515869140625,0.9999982118606567,123.61213684082031,348.5719909667969,0.9999825954437256,128.9623565673828,350.0534973144531,0.9999898672103882,123.19417572021484,355.08074951171875,0.9999990463256836,230.3530731201172,320.119873046875,0.9999847412109375,277.0859069824219,309.77069091796875,0.9999845027923584,247.98236083984375,310.75433349609375,0.9999958276748657,251.8418426513672,307.3601379394531,0.9999945163726807,255.7158203125,310.53167724609375,0.999988317489624,251.15814208984375,314.7593994140625,0.9999648332595825,240.3489532470703,459.19866943359375,0.9999091625213623
</code></pre>

If yours is formatted the same, it should just work without any additional transformations.

**Comment by Rangel07** [comment]
Hey @zdarsky,

I think I expressed my self poorly, I don't know how to create/generate this CSV from the DeepLabCut. All I did was run `gazerec.py` to get the data.

After running `gazerec.py`, how do I use the DeepLabCut to generate the CSV like the one you mentioned? I couldn't find how to do it...

Thanks again!

**Comment by zdarsky** [comment]
I can recommend the instructions of DeepLabCut (DLC), when I was actively working on this project, I mainly used their paper (it should be this: https://www.nature.com/articles/s41596-019-0176-0) but there are also other resources like their homepage (https://deeplabcut.github.io/DeepLabCut/docs/UseOverviewGuide.html) or their GitHub (https://github.com/DeepLabCut/DeepLabCut). I used an old version of DLC, so I can imagine they streamlined the ease of use even more, and it was already very self-explaining back in the day as everything came with nice GUI tools.

After you installed their DLC tool, you need to annotate the points of interest of a face / multiple faces (eyes + upper lip) for some video frames. Afterwards, you train DLC with the data you just created. You can then use that trained model to extract the CSV I posted above from newly recorded videos.
